name: heeve
description: A game for GitHub's GameOff 2021
version: 0.1.0
homepage: https://github.com/bluefireteam/heeve

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  dartlin: ^0.6.1
  flame: ^1.0.0-releasecandidate.18
  flame_audio: ^1.0.0-rc.15
  flame_fire_atlas: ^1.0.0-rc2
  a_star_algorithm: ^0.1.1
  ordered_set: ^5.0.0
  google_fonts: ^2.1.0

dev_dependencies:
  flame_lint: ^0.0.1
  dartdoc: ^0.42.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  assets:
    - assets/images/
    - assets/sprites/
    - assets/audio/
    - assets/sprites/humans/
    - assets/sprites/heeves/
  fonts:
    - family: Fredericka
      fonts:
        - asset: assets/fonts/FrederickatheGreat-Regular.ttf
    - family: Sigmar
      fonts:
        - asset: assets/fonts/SigmarOne-Regular.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
